# Generated by Django 4.1.1 on 2022-11-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Profissao',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='categoria',
            new_name='profissao',
        ),
    ]
