# Generated by Django 4.1.1 on 2022-11-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0002_rename_categoria_profissao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='contato',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=7),
        ),
    ]
