# Generated by Django 4.1.1 on 2022-11-09 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0003_contracttype_contato_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='contract_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='func.contracttype'),
        ),
    ]
